# Generated by Django 5.1 on 2024-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_is_sale_category_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale_forthisproduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_forthisproduct',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
