# Generated by Django 5.1 on 2024-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_is_sale_forthisproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sale_price',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price_forthisproduct',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
