# Generated by Django 5.1 on 2024-08-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_sale',
            new_name='osale',
        ),
    ]
